### ISSUE TITLE
code

### ISSUE THREAD

**Issue by DWBSIC** [scott-yjyang/DiffMIC#1]
Hello, thank you very much for your research contribution, when will you open the source code?

您好，非常感谢您的研究贡献，请问您什么时候开源代码呢

**Comment by scott-yjyang** [comment]
Thanks for your attention.
We will open source code when this paper is accepted.

**Comment by DWBSIC** [comment]
> Thanks for your attention. We will open source code when this paper is accepted.

I look forward to your research being accepted by the Top Journals or Top Conferences soon!
